name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v8
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue has been marked as stale due to inactivity. If it's still relevant, please comment or update."
          close-issue-message: "Closing this issue due to inactivity. Feel free to reopen if needed!"
          stale-pr-message: "This pull request has been marked as stale. Please update it if you'd like to keep it open."
          close-pr-message: "Closing this pull request due to inactivity."
